# Generated by Django 3.2.16 on 2022-10-31 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='observation',
            field=models.CharField(max_length=255, null=True, verbose_name='observation'),
        ),
    ]
