# Generated by Django 3.2.16 on 2022-11-02 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0002_alter_entry_observation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=11, null=True, verbose_name='balance'),
        ),
    ]
