# Generated by Django 3.2.16 on 2022-11-02 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0003_alter_wallet_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='type',
            field=models.CharField(choices=[('GN', 'generic'), ('CO', 'correction'), ('BK', 'bank'), ('CD', 'card')], default='GN', max_length=2, verbose_name='type'),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='balance',
            field=models.DecimalField(decimal_places=2, max_digits=11, null=True, verbose_name='balance'),
        ),
    ]
