# Generated by Django 3.2.16 on 2022-11-02 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0004_auto_20221102_2157'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entry',
            options={'ordering': ['updated', 'id'], 'verbose_name': 'entry', 'verbose_name_plural': 'entries'},
        ),
        migrations.AlterField(
            model_name='entry',
            name='observation',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='observation'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='tags',
            field=models.ManyToManyField(null=True, to='budgets.Tag', verbose_name='tags'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='value',
            field=models.DecimalField(decimal_places=2, max_digits=9, verbose_name='valor'),
        ),
    ]
