# Generated by Django 3.2.16 on 2022-11-08 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0008_alter_entry_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='tags',
            field=models.ManyToManyField(blank=True, to='budgets.Tag', verbose_name='tags'),
        ),
    ]
